name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    name: Build on macOS
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "16.2"
    
    - name: Install macOS dependencies
      run: |
        brew install openssl@3 cmake
    
    - name: Run package script
      run: ./package-mac.sh
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macOS-package
        path: '*.zip'
        
  build-windows:
    runs-on: windows-latest
    name: Build on Windows

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup MSVC + CMake (C++20)
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install Windows dependencies (CMake + OpenSSL 3)
      run: |
        choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' --yes
        choco install openssl --yes

    - name: Run package script
      run: cmd /c package.bat

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-package
        path: '*.zip'
